# -*- coding: utf-8 -*-
"""
  create-x source code grading and score.
  base type definition.
  
  Xi'an Feidie VR technology co. LTD
  2019/10/08
"""

# ##### control type ######
CT_NONE = -1
CT_COMBOBOX = 0
CT_NUMBERBOX = 1
CT_CONDITIONBOX = 2
CT_TEXTBOX = 3
CT_MUSICBOX = 4
CT_CHANGEABLE = 5  # 2019/12/11 added

# ##### parameter type ######
PARAMTYPE_SD_HUMANACTION = 0x0000000000000001
PARAMTYPE_SD_BOARDKEY = 0x0000000000000002
PARAMTYPE_SD_PICOKEY = 0x0000000000000004
PARAMTYPE_SD_COORDINATESYSTEM = 0x0000000000000008
PARAMTYPE_SD_COORDINATE3 = 0x0000000000000010
PARAMTYPE_SD_COORDINATE9 = 0x0000000000000020
PARAMTYPE_SD_RESOURCE = 0x0000000000000040
PARAMTYPE_SD_RESOURCEUI = 0x0000000000000080
PARAMTYPE_SD_RESOURCEACTION = 0x0000000000000100
PARAMTYPE_SD_PICOFACILITY = 0x0000000000000200
PARAMTYPE_SD_RUNTIMEENV = 0x0000000000000400
PARAMTYPE_SD_NUMBERTYPE = 0x0000000000000800
PARAMTYPE_SD_OPERATORCOMPARE = 0x0000000000001000
PARAMTYPE_SD_OPERATORBOOL = 0x0000000000002000
PARAMTYPE_SD_OPERATORARITHMETIC = 0x0000000000004000
PARAMTYPE_SD_OPERATORFUNCTION = 0x0000000000008000
PARAMTYPE_SD_OPERATORTRIFUNCTION = 0x0000000000010000
PARAMTYPE_SD_VARIABLES = 0x0000000000020000
PARAMTYPE_SD_VARIABLESINCDEC = 0x0000000000040000
PARAMTYPE_SD_NUMBER = 0x0000000000080000
PARAMTYPE_SC_BLK_VARIABLES = 0x0000000000100000
PARAMTYPE_SC_BLKTYPE_DATACAL = 0x0000000000200000
PARAMTYPE_SC_BLKTYPE_CONDITION = 0x0000000000400000
PARAMTYPE_SD_TEXT = 0x0000000000800000
PARAMTYPE_SD_SOUND = 0x0000000001000000
PARAMTYPE_SC_BLK_RESOURCE = 0x0000000002000000  # 2019/12/11 added
PARAMTYPE_SD_CHANGEABLE = 0x0000000004000000  # 2019/12/11 added
PARAMTYPE_SD_MOUSEKEY = 0x0000000008000000
PARAMTYPE_SD_LOOP = 0x0000000010000000
PARAMTYPE_SD_WHILE = 0x0000000020000000
PARAMTYPE_SD_OBJECT = 0x0000000040000000
PARAMTYPE_SD_STATE = 0x0000000080000000
PARAMTYPE_SD_TYPE = 0x0000000100000000
PARAMTYPE_SD_PEN = 0x0000000200000000
PARAMTYPE_SD_COLOR = 0x0000000400000000

# ###### parameter type(base on sequence and control type),for parameter default value
ARGTYPE_INPUTFIELD_NUMTEXT = 1  # inputField
ARGTYPE_DROPDOWN = 2  # dropdown
ARGTYPE_DROPDOWN2 = 3  # dropdown2
ARGTYPE_OBJECTDROPDOWN = 4  # objectdoropdown
ARGTYPE_UIDROPDOWN = 5  # UIdropdown
ARGTYPE_OBJECTDROPDOWN = 6  # objectdoropdown2
ARGTYPE_TEXT_MUSIC = 7  # text
ARGTYPE_DROPDOWN3 = 8  # dropdown3
ARGTYPE_CONDITION = 9  # condition no default value

###### block type ######
BLKTYPE_TRIGGER = 0x0000000000000001
BLKTYPE_LOGICFLOW = 0x0000000000000002
BLKTYPE_OBJECTACTION = 0x0000000000000004
BLKTYPE_OBJECTSETTING = 0x0000000000000008
BLKTYPE_CONDITION = 0x0000000000000010
BLKTYPE_VARIABLES = 0x0000000000000020
BLKTYPE_PHYSICSFEATHER = 0x0000000000000040
BLKTYPE_SOUND = 0x0000000000000080
BLKTYPE_DATACAL = 0x0000000000000100
BLKTYPE_FUNCTION = 0x0000000000000200
BLKTYPE_DRAW = 0x0000000000000400

# ##### block subtype ######
BLKSUBTYPE_START = 0x0000000000000001
BLKSUBTYPE_CONTAINERLOOP1 = 0x0000000000000002
BLKSUBTYPE_CONTAINERLOOP1END = 0x0000000000000004
BLKSUBTYPE_CONTAINERCOND1 = 0x0000000000000008
BLKSUBTYPE_CONTAINERCOND1END = 0x0000000000000010
BLKSUBTYPE_CONTAINERCOND2 = 0x0000000000000020
BLKSUBTYPE_CONTAINERCOND2END1 = 0x0000000000000040
BLKSUBTYPE_CONTAINERCOND2END2 = 0x0000000000000080
BLKSUBTYPE_SEQUENCE_BOTTOM = 0x0000000000000100
BLKSUBTYPE_SEQUENCE_TOP = 0x0000000000000200
BLKSUBTYPE_SEQUENCE_TOPBOTTOM = 0x0000000000000400
BLKSUBTYPE_BREAK = 0x0000000000000800
BLKSUBTYPE_EMBEDCHILD4C = 0x0000000000001000
BLKSUBTYPE_EMBEDCHILD4V = 0x0000000000002000
BLKSUBTYPE_DELAY_WAIT = 0x0000000000004000
BLKSUBTYPE_DELAY_NOWAIT = 0x0000000000008000
BLKSUBTYPE_OPEN_PHYSICSENGINE = 0x0000000000010000
BLKSUBTYPE_RELYON_PHYSICSENGINE = 0x0000000000020000
BLKSUBTYPE_CLOSE_PHYSICSENGINE = 0x0000000000040000
BLKSUBTYPE_TRIGGER = 0x0000000000080000
BLKSUBTYPE_GAMEOVER = 0x0000000000100000
BLKSUBTYPE_BROTHER_WORK = 0x0000000000200000  # 支持21

# ##### block referrence dictionary ######
BLKREFID_TRG_WHENPROJECTSTART = 4  # 【触发01】: 当工程运行时
BLKREFID_TRG_WHENSELFBEENCLICK = 5  # 【触发02】: 当自己被点击
BLKREFID_TRG_WHENRECIEVEBROADCASTMESSAGE = 7  # 【触发03】: 当收到广播 (广播消息编号)
BLKREFID_TRG_WHENCONDITION = 6  # 【触发04】: 当 <条件表达式>
BLKREFID_TRG_WHENRUNNINGASCLONE = 8  # 【触发05】: 当作为克隆体启动时
BLKREFID_TRG_WHENMOUSEMOVING = 68  # 【触发06】: 当鼠标[移入|移出]自己时
BLKREFID_TRG_WHENKEYBOARDACTION = 67  # 【触发07】: 当键盘[按下|抬起|持续按下][按键|......]时
BLKREFID_TRG_WHENPICOHANDLECURSOR = 10  # 【触发08】: 当pico手柄指向
BLKREFID_TRG_WHENMOUSEKEY_CLICK = 160  # 【触发09】: 自己被鼠标 左键/右键/中键 点击
BLKREFID_TRG_WHENMOUSEKEY_UPDOWN = 159  # 【触发10】: 鼠标 左键/右键/中键 按下/松开
BLKREFID_TRG_WHENTOUCHSCREEN_CLICK = 156  # 【触发11】: 自己以触屏被点击
BLKREFID_TRG_WHENVKEYBOARD_CLICK = 153  # 触发12】: 虚拟键盘 按下/抬起/持续按下 A/B/上/下/左/右
BLKREFID_TRG_WHENBESTARED = 158  # 【触发13】: 自己被目视
BLKREFID_TRG_WHENVRHANDLE_CLICK = 157  # 【触发14】: 当pico手柄 圆盘键/扳机键 点击自己
BLKREFID_TRG_WHENVRHANDLE_UPDOWN = 170  # 【触发15】: 当pico手柄 按下/松开/持续按下 圆盘键/扳机键/上/下/左/右
BLKREFID_TRG_WHENPICOHANDLEACTION = 9  # 【触发16】: 当pico手柄[按下|松开][圆盘键|扳机键]【old,支持】
BLKREFID_TRG_WHENMOUSELEFTKEYACTION = 69  # 当鼠标左键[按下|松开]时【old,暂不支持】
BLKREFID_FUNCTION_NOHAS_RETURNVALUE = 148  # 【自定义函数01】: 没有返回值
BLKREFID_FUNCTION_HAS_RETURNVALUE = 149  # 【自定义函数02】: 有返回值
BLKREFID_FUNCTION_NOHAS_CALL = 150  # 【顺序01】: 没有返回值的函数的调用块
BLKREFID_FUNCTION_HAS_CALL = 152  # 【可嵌入01】，有返回值的函数的调用
BLKREFID_FUNCTION_PARAMLIST = 151  # 【可嵌入02】，函数参数列表，每个资源或者class下面的自定义函数公用
BLKREFID_LF_LOOPUNLIMITED = 17  # 【1】while(true),重复执行
BLKREFID_LF_LOOPNUMBER = 16  # 【2】for in range(n),重复执行(n次)
BLKREFID_LF_LOOPSTOP = 117  # 【顺序02】: break/continue
BLKREFID_LF_WAITNUMBERSECONDS = 22  # 【顺序03】: wait(n秒)
BLKREFID_LF_LOOP_WHILE_WHILENOT = 116
BLKREFID_LF_LOOP_STEP = 123  # 【4】for start end step
BLKREFID_LF_LOOP_TRAVERSELIST = 139  # 【5】foreach item in list
BLKREFID_LF_IFELSE_PLUS = 119  # 【6】if ... elseif ... + [elseif ... +] + else
BLKREFID_LF_IF = 23  # 【7】如果<条件表达式> 【old】
BLKREFID_LF_IFELSE = 19  # 【8】如果<条件表达式>,否则 【old】支持
BLKREFID_LF_TELLOBJECT2EXCUTING = 21  # 告诉其他对象执行 支持21, 【old, 暂不支持】
BLKREFID_OA_MOVINGRXYZINTIMEBYCOORDINATE = 98  # 【顺序04】: 在(n)秒内,移动(x)(y)(z)[自身坐标系|世界坐标系]
BLKREFID_OA_MOVINGRXYZBYCOORDINATE = 96  # 【顺序05】: 移动距离(x)(y)(z)[自身坐标系|世界坐标系]
BLKREFID_OA_MOVINGAXYZINTIMEBYCOORDINATE = 103  # 【顺序06】: 在(n)秒内,移动到(x)(y)(z)[自身坐标系|世界坐标系]
BLKREFID_OA_ROTATERXYZINTIMEBYCOORDINATE = 95  # 【顺序07】: 在(n)秒内,旋转角度(x)(y)(z)[自身坐标系|世界坐标系]
BLKREFID_OA_ROTATERXYZBYCOORDINATE = 97  # 【顺序08】: 旋转角度(x)(y)(z)[自身坐标系|世界坐标系]
BLKREFID_OA_ROTATEAXYZINTIMEBYCOORDINATE = 104  # 【顺序09】: 在(n)秒内,旋转到(x)(y)(z)[自身坐标系|世界坐标系]
BLKREFID_OA_RESIZEPERSENT = 34  # 【顺序10】: 在(n)秒内,将大小改变为(n)%
BLKREFID_OA_PLAYRESOURCEACTION = 30  # 【顺序11】: 播放动作(资源的动作|......)
BLKREFID_OA_STOPRESOURCEACTION = 31  # 【顺序12】: 停止动作
BLKREFID_OA_DISPLAYTEXTONTOP = 13  # 【顺序13】: 顶部显示文字(显示文字)
BLKREFID_OA_UNDISPLAYTEXTONTOP = 14  # 【顺序14】: 关闭头顶文字
BLKREFID_OA_BREAKRESOURCE2XYZ = 18  # 【顺序15】: 分裂[资源]到(x)(y)(z)
BLKREFID_OA_DISPLAYTEXTINUIRESOURCE = 94  # 【顺序16】: UI资源[资源]文字显示为(显示文字)
BLKREFID_OA_RESIZEVECTORWITHTIME = 36  # 【顺序17】:  n秒内将长度，宽度，高度改变为n%
BLKREFID_OA_DISPLAYTEXTINUIRESOURCEPLUS = 202  # 【顺序16】: UI资源[资源]文字显示为(显示文字+)
BLKREFID_OS_DELETESELF = 1  # 【顺序18】: 删除自己
BLKREFID_OS_DISPLAYRESOURCE = 101  # 【顺序19】: 显示[资源]
BLKREFID_OS_HIDERESOURCE = 102  # 【顺序20】: 隐藏[资源]
BLKREFID_OS_TOBESUBRESOURCEOFPICOFACILITYINOVERLAPPING = 38  # 【顺序21】: 成为[头盔|手柄]子物体并重叠
BLKREFID_OS_TOBESUBRESOURCEOFRESOURCEINOVERLAPPING = 40  # 【顺序22】: 成为[资源]子物体并重叠
BLKREFID_OS_TOBESUBRESOURCEOFPICOFACILITYINORIGINALSTATE = 87  # 【顺序23】: 成为[头盔|手柄]子物体并保持现状
BLKREFID_OS_TOBESUBRESOURCEOFRESOURCEINORIGINALSTATE = 88  # 【顺序24】: 成为[资源]子物体并保持现状
BLKREFID_OS_BREADAWAYFROWPARENTRESOURCE = 11  # 【顺序25】: 脱离父物体
BLKREFID_OS_GAMEOVER = 12  # 【顺序26】: 工程结束运行
BLKREFID_OS_CLONERESOURCE = 3  # 【顺序27】: 克隆[资源]
BLKREFID_OS_BROADCASTMESSAGE_P2P = 111  # 【顺序28】: 发送广播(msgID,object)
BLKREFID_OS_SHOWVKB = 154  # 【顺序29】: 显示虚拟键盘
BLKREFID_OS_HIDEVKB = 155  # 【顺序30】: 隐藏虚拟键盘
BLKREFID_OS_OPENSSCREEN = 172  # 【顺序31】: 打开滑屏
BLKREFID_OS_CLOSESSCREEN = 173  # 【顺序32】: 关闭滑屏
BLKREFID_OS_SWITCHSTARE = 174  # 【顺序33】: 开启/关闭 注视 资源
BLKREFID_OS_BROADCASTMESSAGE = 2  # 发送广播(广播消息编号) ,【old】支持
BLKREFID_OS_DISPLAY = 32  # 显示,【old】 支持
BLKREFID_OS_HIDE = 33  # 隐藏, 【old】 支持
BLKREFID_CND_CRACHRESOURCE = 46  # 【可嵌入条件框01】: 自己碰到[资源]
BLKREFID_CND_NUMBERISOJZZZF = 50  # 【可嵌入条件框02】: (数字)是[偶数|奇数|质数|整数|正数|负数]
BLKREFID_CND_EXACTDIVISION = 51  # 【可嵌入条件框03】: (数字)能被(数字)整除
BLKREFID_CND_BOOLANDOR = 52  # 【可嵌入条件框04】: <条件表达式>[且|或]<条件表达式>
BLKREFID_CND_BOOLCOMPARE = 56  # 【可嵌入条件框05】: (数字)[=|!=|<|<=|>|>=](数字)
BLKREFID_CND_BOOLNOT = 57  # 【可嵌入条件框06】: <条件表达式>不成立
BLKREFID_CND_CAPTURE = 86  # 【可嵌入条件框07】: [资源]被抓取
BLKREFID_CND_CHECKTYPE = 120  # 【可嵌入条件框08】: 判断类型是否是int/float/string/list
BLKREFID_CND_BOOLEANCONSTANT = 122  # 【可嵌入条件框09】: 布尔常量true/false
BLKREFID_CND_CONVERT2BOOLTYPE = 126  # 【可嵌入条件框10】: 转为bool类型
BLKREFID_CND_EXISTINSTRING = 128  # 【可嵌入条件框11】: 是否在string中
BLKREFID_CND_EXISTINLIST = 144  # 【可嵌入条件框12】: 是否在list中
BLKREFID_CND_COLLISIONCLONE = 203  # 【可嵌入条件框13】: 是否碰到一个物体的克隆
BLKREFID_CND_RUNTIMEENV = 92  # 【可嵌入条件框14】: 运行平台为[PC平台|VR平台]
BLKREFID_CND_MOUSE_KEY_UPDOWN = 161  # 【可嵌入条件框15】: 鼠标左键/右键/中键 按下/松开
BLKREFID_CND_MOUSE_MOVE = 162  # 【可嵌入条件框16】: 鼠标移入/移出 自己
BLKREFID_CND_KB_KEY_UPDOWN = 163  # 【可嵌入条件框17】: 键盘按下/抬起/持续按下 keys
BLKREFID_CND_MOUSE_KEY_CLICK = 164  # 【可嵌入条件框18】: 当自己被鼠标左键/右键/中键 点击
BLKREFID_CND_VKB_KEY_UPDOWN = 165  # 【可嵌入条件框19】: 虚拟键盘按下/抬起/持续按下 A/B/上/下/左/右
BLKREFID_CND_CLICK = 166  # 【可嵌入条件框20】: 自己被点击
BLKREFID_CND_STARE = 167  # 【可嵌入条件框21】: 自己被目视
BLKREFID_CND_VRHANDLE_KEY_UPDOWN = 171  # 【可嵌入条件框22】: 手柄按下/松开/持续按下 圆盘键/扳机键/上/下/左/右
BLKREFID_CND_VRHANDLE_KEY_CLICK = 168  # 【可嵌入条件框23】: 自己被手柄圆盘键/扳机键 点击
BLKREFID_CND_VRHANDLE_POINT = 169  # 【可嵌入条件框24】: 手柄指向自己
BLKREFID_CND_POCIKEYDOWNRELEASE = 45  # 【可嵌入条件框】: [按下|松开][圆盘键|扳机键]  【old】
BLKREFID_CND_ADSORPTION = 85  # 【可嵌入条件框】: [资源]被[资源]吸附 【old】
BLKREFID_VAR_VARIABLES = 59  # 【可嵌入01】:[可嵌入数字框]: 变量框
BLKREFID_VAR_STRING = 109  # 【可嵌入02】: 镶嵌一个需要输入的字符串内容
BLKREFID_VAR_OBJECT = 110  # 【可嵌入03】: 镶嵌数据为某个资源，取值时取该资源在列表中的序
BLKREFID_VAR_LIST = 112  # 【可嵌入04】: 镶嵌内空为一个列表，可为列表添加项
BLKREFID_VAR_LIST_GET = 114  # 【可嵌入05】: 获取关联为列表的变量所对应列表的某一顶内容
BLKREFID_VAR_STRING_JOINT = 125  # 【可嵌入06】: 拼接字符串
BLKREFID_VAR_STRING_GETLENGTH = 127  # 【可嵌入07】: 获取字符串长度
BLKREFID_VAR_STRING_SUBCOUNT = 129  # 【可嵌入08】: 获取子串数目
BLKREFID_VAR_STRING_FUNCTION = 130  # 【可嵌入09】: 字符串通用函数
BLKREFID_VAR_STRINGCHAR = 131  # 【可嵌入10】: 字符串的第几个字符(串)
BLKREFID_VAR_STRINGLASTCHAR = 132  # 【可嵌入11】: 字符串的最后一个字符(串)
BLKREFID_VAR_STRINGSUBSTRPICK = 133  # 【可嵌入12】: 取子串(间隔抽取)
BLKREFID_VAR_STRINGJOINTBYTOKEN = 134  # 【可嵌入13】: list连接成字符串
BLKREFID_VAR_STRINGSPLITLIMITCOUNT = 135  # 【可嵌入14】: 拆分成列表(,生成n项)
BLKREFID_VAR_STRINGSUB = 136  # 【可嵌入15】: 获取子串
BLKREFID_VAR_STRINGSUBCOUNT = 137  # 【可嵌入16】: 子串数目
BLKREFID_VAR_STRINGREPLACE = 138  # 【可嵌入17】: 子串替换
BLKREFID_VAR_LISTLASTITEM = 178  # 【可嵌入18】: 列表的最后一项
BLKREFID_VAR_VARIABLESINCDEC = 60  # 【顺序34】: 使变量[变量][增加|减少](数字)
BLKREFID_VAR_VARIABLESASSIGNMENT = 62  # 【顺序35】: 设置变量[变量]的值为(数字)
BLKREFID_VAR_LIST_SET = 113  # 【顺序36】: 将关联为列表的变量所对应的列表某一项替换为指定内容
BLKREFID_VAR_LOG = 115  # 【顺序37】: 输出指定的log内容
BLKREFID_VAR_LIST_APPEND = 140  # 【顺序38】: list append
BLKREFID_VAR_LIST_INSERT = 141  # 【顺序39】: list insert
BLKREFID_VAR_LIST_REMOVE = 142  # 【顺序40】: list remove
BLKREFID_VAR_LISTSORT = 143  # 【顺序41】: list sort
BLKREFID_VAR_PLUSEQUEAL = 145  # 【顺序42】: 变量 += contants
BLKREFID_VAR_REMOVETAIL = 175  # 【顺序43】: list remove tail
BLKREFID_PF_STARTPHYSICSENGINE = 70  # 【顺序44】: 开启物理引擎
BLKREFID_PF_STOPPHYSICSENGINE = 71  # 【顺序45】: 关闭物理引擎
BLKREFID_PF_SETTINGMASS = 72  # 【顺序46】: 设置质量(数字)
BLKREFID_PF_OPENGRAVITY = 89  # 【顺序47】: 开启重力
BLKREFID_PF_CLOSEGRAVITY = 79  # 【顺序48】: 关闭重力
BLKREFID_PF_FORCEFROMXYZBYCOORDINATE = 108  # 【顺序49】: n秒内受到[x|y|z]方向的力(数字)N ，坐标
BLKREFID_PF_TOBETRIGGER = 99  # 【顺序50】: 设为触发器
BLKREFID_PF_TOBECOLLIDER = 100  # 【顺序51】: 设为碰撞器
BLKREFID_PF_OPEN_COLLIDE = 205  # 【顺序52】: 开启碰撞
BLKREFID_PF_CLOSE_COLLIDE = 204  # 【顺序53】: 关闭碰撞
BLKREFID_SD_PLAYSOUNDREPEAT = 41  # 【顺序54】: 播放声音(音乐导入框)重复
BLKREFID_SD_PLAYSOUNDONCE = 39  # 【顺序55】: 播放声音(音乐导入框)一次
BLKREFID_SD_STOPSOUND = 43  # 【顺序56】: 停止播放声音
BLKREFID_SD_TTS_START = 179  # 【顺序57】: 用xx声音说yy
BLKREFID_SD_TTT_END = 180  # 【顺序58】: 停止播放语音
BLKREFID_DC_VARIABLECELL = 47  # 【可嵌入1】: (数字)
BLKREFID_DC_ARITHMETIC = 48  # 【可嵌入2】: (数字)[+|-|*|/](数字)
BLKREFID_DC_RANDOMNUMBER = 49  # 【可嵌入4】: 在(数字)和(数字)间随机选一个数
BLKREFID_DC_REMAINDER = 54  # 【可嵌入5】: (数字)/(数字)的余数
BLKREFID_DC_GETRESOURCECOORDINATEXYZ3RA = 105  # 【可嵌入6】: [资源]的[x坐标|y坐标|z坐标|x旋转|y旋转|z旋转|x缩放|y缩放|z缩放][自身坐标系|世界坐标系]
BLKREFID_DC_DISTANCEOF2RESOURCE = 63  # 【可嵌入7】: [资源]到[资源]的距离
BLKREFID_DC_TEXTOFRESOUREUI = 93  # 【可嵌入8】: 输入框[资源]的内容
BLKREFID_DC_FUNCTIONPLUS = 118  # 【可嵌入3】: 数学函数，三角函数
BLKREFID_DC_TYPE_TRANSLATE = 124  # 【可嵌入9】: 类型转化
BLKREFID_DC_GET_CURRENTTIME = 121  # 【可嵌入10】: 获取当前时间
BLKREFID_DC_PIE = 146  # 【可嵌入11】: pi,e
BLKREFID_DC_STATICTICS = 147  # 【可嵌入12】: 统计函数
BLKREFID_DC_FLOORCEIL = 177  # 【可嵌入13】: 上下取整
BLKREFID_DC_ROUND = 176  # 【可嵌入14】: 四舍五入(保留有效位)
BLKREFID_DC_GET_TIMEITEM = 206  # 【可嵌入15】: 获取当前年/月/日/星期/小时/分钟/秒
BLKREFID_DC_FUNCTION = 53  # 【可嵌入】: [算数平方根|绝对值|取整|四舍五入取整](数字) 【old】
BLKREFID_DC_TRIFUNCTION = 55  # 【可嵌入】: [sin|cos|tan|cot](数字)度【old】
BLKREFID_DRAW_MOVE = 181  # 【可嵌入】:[画笔] [向前/向后] 移动 [数值]
BLKREFID_DRAW_ROTATE = 182  # 【可嵌入】:[画笔] [向右/向左] 旋转 [数值]
BLKREFID_DRAW_MOVETO = 183  # 【可嵌入】:[画笔] 移动X[数值] Y[数值]
BLKREFID_DRAW_XYMOVETO = 184  # 【可嵌入】:[画笔] [X/Y] 坐标设置为 [数值]
BLKREFID_DRAW_DRAWCIRCLE = 185  # 【可嵌入】:[画笔] 绘制 圆,半径 [数值]【弧，角度[数值]】
BLKREFID_DRAW_DRAWPOLYGONS = 187  # 【可嵌入】:[画笔] 绘制[数值]边形 外接圆半径[数值]
BLKREFID_DRAW_DRAWDOT = 188  # 【可嵌入】:[画笔] 绘制点 直径[数值]
BLKREFID_DRAW_DRAWTEXT = 186  # 【可嵌入】:[画笔] 文字印章[文字]【字号[数值] 类型[正常/倾斜/加粗]】
BLKREFID_DRAW_BRUSH = 189  # 【不可修改】: [画笔]
BLKREFID_DRAW_SETNEWBRUSH = 190  # 【可嵌入】:设置 [变量名] 为新画笔
BLKREFID_DRAW_FACINGANGLE = 191  # 【可嵌入】:[画笔]面向[数值]度
BLKREFID_DRAW_BRUSHSTATE = 192  # 【可嵌入】:[画笔] [落笔/抬笔]
BLKREFID_DRAW_BRUSHTHICKNESS = 193  # 【可嵌入】:设置[画笔]粗细[数值]
BLKREFID_DRAW_BRUSHSPEED = 194  # 【可嵌入】:设置[画笔]速度[数值]
BLKREFID_DRAW_GETBRUSHVALUE = 195  # 【可嵌入】:获取[画笔][x/y]坐标
BLKREFID_DRAW_SHOWORHIDEBRUSH = 196  # 【可嵌入】:[隐藏/显示][画笔]
BLKREFID_DRAW_CLEARBRUSH = 197  # 【可嵌入】:清空[画笔]
BLKREFID_DRAW_STOPBRUSH = 198  # 【不可修改】:画笔停止运行
BLKREFID_DRAW_SETBACKGROUNDCOLOR = 200  # 【不可嵌入】:设置背景颜色
BLKREFID_DRAW_SETBRUSHCOLOR = 201  # 【不可嵌入】:设置[画笔]颜色
BLKREFID_DRAW_PRINT = 207  # 填写方式：【可嵌入】:
BLKREFID_DRAW_ASKANDINPUT = 208  # 填写方式：【可嵌入】:
BLKREFID_DRAW_GETINPUT = 209  # 填写方式：【可嵌入】:
BLKREFID_DRAW_OTHERPYTHONFUNCTION = 210  # 填写方式：【暂定不可嵌入】:

# 2021-10-14 新增
BLKREFID_VAR_LOCALVARIABLES = 211
BLKREFID_LF_LOOP_STEP_NEW = 212  # 【4】for start end step
BLKREFID_LF_LOOP_TRAVERSELIST_NEW = 213  # 【5】foreach item in list
BLKREFID_CND_EXISTINLIST_NEW = 214  # 【可嵌入条件框12】: 是否在list中
BLKREFID_VAR_VARIABLESINCDEC_NEW = 215  # 【顺序34】: 使变量[变量][增加|减少](数字)
BLKREFID_VAR_VARIABLESASSIGNMENT_NEW = 216  # 【顺序35】: 设置变量[变量]的值为(数字)
BLKREFID_VAR_LIST_SET_NEW = 217  # 【顺序36】: 将关联为列表的变量所对应的列表某一项替换为指定内容
BLKREFID_VAR_LIST_GET_NEW = 218  # 【可嵌入05】: 获取关联为列表的变量所对应列表的某一顶内容
BLKREFID_VAR_STRINGJOINTBYTOKEN_NEW = 219  # 【可嵌入13】: list连接成字符串
BLKREFID_VAR_STRINGSUB_NEW = 220  # 【可嵌入15】: 获取子串
BLKREFID_VAR_LIST_APPEND_NEW = 221  # 【顺序38】: list append
BLKREFID_VAR_LIST_INSERT_NEW = 222  # 【顺序39】: list insert
BLKREFID_VAR_LIST_REMOVE_NEW = 223  # 【顺序40】: list remove
BLKREFID_VAR_LISTSORT_NEW = 224  # 【顺序41】: list sort
BLKREFID_VAR_PLUSEQUEAL_NEW = 225  # 【顺序42】: 变量 += contants
BLKREFID_VAR_REMOVETAIL_NEW = 226  # 【顺序43】: list remove tail
BLKREFID_VAR_LISTLASTITEM_NEW = 227  # 【可嵌入18】: 列表的最后一项
BLKREFID_DC_STATICTICS_NEW = 228  # 【可嵌入12】: 统计函数
BLKREFID_DC_RANDOMINT = 229  # 【可嵌入】
BLKREFID_OA_MOVEBYPATHWITHTIME = 230
BLKREFID_LF_LOOP_DEFAULT = 231


# ##### block attribute dictionary ######
BLKATTR_CATEGORY = 0
# BLKATTR_SUBCATEGORY = 1
# BLKATTR_NAME = 2
BLKATTR_PARAMETERCOUNT = 1
BLKATTR_ARGTYPE = 2
BLKATTR_CONTROLTYPE = 3

DictBlockAttribute = {
    BLKREFID_TRG_WHENPROJECTSTART: (BLKTYPE_TRIGGER, 0, (), (CT_NONE, )),
    BLKREFID_TRG_WHENSELFBEENCLICK: (BLKTYPE_TRIGGER, 0, (), (CT_NONE, )),
    BLKREFID_TRG_WHENRECIEVEBROADCASTMESSAGE:
    (BLKTYPE_TRIGGER, 1, (PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
                          | PARAMTYPE_SC_BLKTYPE_DATACAL, ), (CT_NUMBERBOX, )),
    BLKREFID_TRG_WHENCONDITION: (BLKTYPE_TRIGGER, 1,
                                 (PARAMTYPE_SC_BLKTYPE_CONDITION, ),
                                 (CT_CONDITIONBOX, )),
    BLKREFID_TRG_WHENRUNNINGASCLONE: (BLKTYPE_TRIGGER, 0, (), (CT_NONE, )),
    BLKREFID_TRG_WHENMOUSEMOVING:
    (BLKTYPE_TRIGGER, 1, (PARAMTYPE_SD_HUMANACTION, ), (CT_COMBOBOX, )),
    BLKREFID_TRG_WHENKEYBOARDACTION:
    (BLKTYPE_TRIGGER, 2, (PARAMTYPE_SD_HUMANACTION, PARAMTYPE_SD_BOARDKEY),
     (CT_COMBOBOX, CT_COMBOBOX)),
    BLKREFID_TRG_WHENPICOHANDLECURSOR: (BLKTYPE_TRIGGER, 0, (), (CT_NONE, )),
    BLKREFID_TRG_WHENMOUSEKEY_CLICK:
    (BLKTYPE_TRIGGER, 1, (PARAMTYPE_SD_MOUSEKEY, ), (CT_COMBOBOX, )),
    BLKREFID_TRG_WHENMOUSEKEY_UPDOWN:
    (BLKTYPE_TRIGGER, 2, (PARAMTYPE_SD_MOUSEKEY, PARAMTYPE_SD_HUMANACTION),
     (CT_COMBOBOX, CT_COMBOBOX)),
    BLKREFID_TRG_WHENTOUCHSCREEN_CLICK: (BLKTYPE_TRIGGER, 0, (), (CT_NONE, )),
    BLKREFID_TRG_WHENVKEYBOARD_CLICK:
    (BLKTYPE_TRIGGER, 2, (PARAMTYPE_SD_HUMANACTION, PARAMTYPE_SD_BOARDKEY),
     (CT_COMBOBOX, CT_COMBOBOX)),
    BLKREFID_TRG_WHENBESTARED: (BLKTYPE_TRIGGER, 0, (), (CT_NONE, )),
    BLKREFID_TRG_WHENVRHANDLE_CLICK:
    (BLKTYPE_TRIGGER, 1, (PARAMTYPE_SD_PICOKEY, ), (CT_COMBOBOX, )),
    BLKREFID_TRG_WHENVRHANDLE_UPDOWN:
    (BLKTYPE_TRIGGER, 2, (PARAMTYPE_SD_HUMANACTION, PARAMTYPE_SD_PICOKEY),
     (CT_COMBOBOX, CT_COMBOBOX)),
    BLKREFID_TRG_WHENPICOHANDLEACTION: (BLKTYPE_TRIGGER, 2,
                                        (PARAMTYPE_SD_HUMANACTION,
                                         PARAMTYPE_SD_PICOKEY), (CT_COMBOBOX,
                                                                 CT_COMBOBOX)),
    BLKREFID_TRG_WHENMOUSELEFTKEYACTION:
    (BLKTYPE_TRIGGER, 1, (PARAMTYPE_SD_HUMANACTION, ), (CT_COMBOBOX, )),
    BLKREFID_FUNCTION_NOHAS_RETURNVALUE: (BLKTYPE_FUNCTION, 0, (),
                                          (CT_NONE, )),
    BLKREFID_FUNCTION_HAS_RETURNVALUE: (BLKTYPE_FUNCTION, -1,
                                        (PARAMTYPE_SD_CHANGEABLE, ),
                                        (CT_CHANGEABLE, )),
    BLKREFID_FUNCTION_NOHAS_CALL: (BLKTYPE_FUNCTION, -1,
                                   (PARAMTYPE_SD_CHANGEABLE, ), (CT_CHANGEABLE, )),
    BLKREFID_FUNCTION_HAS_CALL: (BLKTYPE_FUNCTION, 0, (), (CT_NONE, )),
    BLKREFID_FUNCTION_PARAMLIST: (BLKTYPE_FUNCTION, 1,
                                  (PARAMTYPE_SD_VARIABLES, ), (CT_COMBOBOX, )),
    BLKREFID_LF_LOOPUNLIMITED: (BLKTYPE_LOGICFLOW, 0, (), (CT_NONE, )),
    BLKREFID_LF_LOOPNUMBER: (BLKTYPE_LOGICFLOW, 1,
                             (PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
                              | PARAMTYPE_SC_BLKTYPE_DATACAL, ),
                             (CT_NUMBERBOX, )),
    BLKREFID_LF_LOOPSTOP: (BLKTYPE_LOGICFLOW, 1, (PARAMTYPE_SD_LOOP, ),
                           (CT_COMBOBOX, )),
    BLKREFID_LF_WAITNUMBERSECONDS:
    (BLKTYPE_LOGICFLOW, 1, (PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
                            | PARAMTYPE_SC_BLKTYPE_DATACAL, ),
     (CT_NUMBERBOX, )),
    BLKREFID_LF_LOOP_WHILE_WHILENOT: (BLKTYPE_LOGICFLOW, 2,
                                      (PARAMTYPE_SD_WHILE,
                                       PARAMTYPE_SC_BLKTYPE_CONDITION),
                                      (CT_COMBOBOX, CT_CONDITIONBOX)),
    BLKREFID_LF_LOOP_STEP: (BLKTYPE_LOGICFLOW, 4,
                            (PARAMTYPE_SC_BLK_VARIABLES, PARAMTYPE_SD_NUMBER,
                             PARAMTYPE_SD_NUMBER, PARAMTYPE_SD_NUMBER),
                            (CT_COMBOBOX, CT_NUMBERBOX, CT_NUMBERBOX,
                             CT_NUMBERBOX)),
    BLKREFID_LF_LOOP_TRAVERSELIST: (BLKTYPE_LOGICFLOW, 2,
                                    (PARAMTYPE_SC_BLK_VARIABLES,
                                     PARAMTYPE_SC_BLK_VARIABLES),
                                    (CT_COMBOBOX, CT_COMBOBOX)),
    BLKREFID_LF_IFELSE_PLUS: (BLKTYPE_LOGICFLOW, 1,
                              (PARAMTYPE_SC_BLKTYPE_CONDITION, ),
                              (CT_CONDITIONBOX, )),
    BLKREFID_LF_IF: (BLKTYPE_LOGICFLOW, 1, (PARAMTYPE_SC_BLKTYPE_CONDITION, ),
                     (CT_CONDITIONBOX, )),
    BLKREFID_LF_IFELSE: (BLKTYPE_LOGICFLOW, 1,
                         (PARAMTYPE_SC_BLKTYPE_CONDITION, ),
                         (CT_CONDITIONBOX, )),
    BLKREFID_LF_TELLOBJECT2EXCUTING: (BLKTYPE_LOGICFLOW, 1,
                                      (PARAMTYPE_SD_RESOURCE, ),
                                      (CT_COMBOBOX, )),
    BLKREFID_OA_MOVINGRXYZINTIMEBYCOORDINATE:
    (BLKTYPE_OBJECTACTION, 5,
     (PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL, PARAMTYPE_SD_NUMBER
      | PARAMTYPE_SC_BLK_VARIABLES | PARAMTYPE_SC_BLKTYPE_DATACAL,
      PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL, PARAMTYPE_SD_NUMBER
      | PARAMTYPE_SC_BLK_VARIABLES | PARAMTYPE_SC_BLKTYPE_DATACAL,
      PARAMTYPE_SD_COORDINATESYSTEM),
     (CT_NUMBERBOX, CT_NUMBERBOX, CT_NUMBERBOX, CT_NUMBERBOX, CT_COMBOBOX)),
    BLKREFID_OA_MOVINGRXYZBYCOORDINATE:
    (BLKTYPE_OBJECTACTION, 4,
     (PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL, PARAMTYPE_SD_NUMBER
      | PARAMTYPE_SC_BLK_VARIABLES | PARAMTYPE_SC_BLKTYPE_DATACAL,
      PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL, PARAMTYPE_SD_COORDINATESYSTEM),
     (CT_NUMBERBOX, CT_NUMBERBOX, CT_NUMBERBOX, CT_COMBOBOX)),
    BLKREFID_OA_MOVINGAXYZINTIMEBYCOORDINATE:
    (BLKTYPE_OBJECTACTION, 5,
     (PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL, PARAMTYPE_SD_NUMBER
      | PARAMTYPE_SC_BLK_VARIABLES | PARAMTYPE_SC_BLKTYPE_DATACAL,
      PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL, PARAMTYPE_SD_NUMBER
      | PARAMTYPE_SC_BLK_VARIABLES | PARAMTYPE_SC_BLKTYPE_DATACAL,
      PARAMTYPE_SD_COORDINATESYSTEM),
     (CT_NUMBERBOX, CT_NUMBERBOX, CT_NUMBERBOX, CT_NUMBERBOX, CT_COMBOBOX)),
    BLKREFID_OA_ROTATERXYZINTIMEBYCOORDINATE:
    (BLKTYPE_OBJECTACTION, 5,
     (PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL, PARAMTYPE_SD_NUMBER
      | PARAMTYPE_SC_BLK_VARIABLES | PARAMTYPE_SC_BLKTYPE_DATACAL,
      PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL, PARAMTYPE_SD_NUMBER
      | PARAMTYPE_SC_BLK_VARIABLES | PARAMTYPE_SC_BLKTYPE_DATACAL,
      PARAMTYPE_SD_COORDINATESYSTEM),
     (CT_NUMBERBOX, CT_NUMBERBOX, CT_NUMBERBOX, CT_NUMBERBOX, CT_COMBOBOX)),
    BLKREFID_OA_ROTATERXYZBYCOORDINATE:
    (BLKTYPE_OBJECTACTION, 4,
     (PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL, PARAMTYPE_SD_NUMBER
      | PARAMTYPE_SC_BLK_VARIABLES | PARAMTYPE_SC_BLKTYPE_DATACAL,
      PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL, PARAMTYPE_SD_COORDINATESYSTEM),
     (CT_NUMBERBOX, CT_NUMBERBOX, CT_NUMBERBOX, CT_COMBOBOX)),
    BLKREFID_OA_ROTATEAXYZINTIMEBYCOORDINATE:
    (BLKTYPE_OBJECTACTION, 5,
     (PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL, PARAMTYPE_SD_NUMBER
      | PARAMTYPE_SC_BLK_VARIABLES | PARAMTYPE_SC_BLKTYPE_DATACAL,
      PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL, PARAMTYPE_SD_NUMBER
      | PARAMTYPE_SC_BLK_VARIABLES | PARAMTYPE_SC_BLKTYPE_DATACAL,
      PARAMTYPE_SD_COORDINATESYSTEM),
     (CT_NUMBERBOX, CT_NUMBERBOX, CT_NUMBERBOX, CT_NUMBERBOX, CT_COMBOBOX)),
    BLKREFID_OA_RESIZEPERSENT:
    (BLKTYPE_OBJECTACTION, 2,
     (PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL, PARAMTYPE_SD_NUMBER
      | PARAMTYPE_SC_BLK_VARIABLES | PARAMTYPE_SC_BLKTYPE_DATACAL),
     (CT_NUMBERBOX, CT_NUMBERBOX)),
    BLKREFID_OA_PLAYRESOURCEACTION: (BLKTYPE_OBJECTACTION, 1,
                                     (PARAMTYPE_SD_RESOURCEACTION, ),
                                     (CT_COMBOBOX, )),
    BLKREFID_OA_STOPRESOURCEACTION: (BLKTYPE_OBJECTACTION, 0, (), (CT_NONE, )),
    BLKREFID_OA_DISPLAYTEXTONTOP: (BLKTYPE_OBJECTACTION, 1,
                                   (PARAMTYPE_SD_TEXT
                                    | PARAMTYPE_SC_BLK_VARIABLES
                                    | PARAMTYPE_SC_BLKTYPE_DATACAL, ),
                                   (CT_TEXTBOX, )),
    BLKREFID_OA_UNDISPLAYTEXTONTOP: (BLKTYPE_OBJECTACTION, 0, (), (CT_NONE, )),
    BLKREFID_OA_BREAKRESOURCE2XYZ:
    (BLKTYPE_OBJECTACTION, 4,
     (PARAMTYPE_SD_RESOURCE, PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL, PARAMTYPE_SD_NUMBER
      | PARAMTYPE_SC_BLK_VARIABLES | PARAMTYPE_SC_BLKTYPE_DATACAL,
      PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL), (CT_COMBOBOX, CT_NUMBERBOX,
                                        CT_NUMBERBOX, CT_NUMBERBOX)),
    BLKREFID_OA_DISPLAYTEXTINUIRESOURCE:
    (BLKTYPE_OBJECTACTION, 2,
     (PARAMTYPE_SD_RESOURCEUI, PARAMTYPE_SD_TEXT | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL), (CT_COMBOBOX, CT_TEXTBOX)),
    BLKREFID_OA_RESIZEVECTORWITHTIME: (BLKTYPE_OBJECTACTION, 3,
                                       (PARAMTYPE_SD_NUMBER,
                                        PARAMTYPE_SD_OBJECT,
                                        PARAMTYPE_SD_NUMBER), (CT_NUMBERBOX,
                                                               CT_COMBOBOX,
                                                               CT_NUMBERBOX)),
    BLKREFID_OA_DISPLAYTEXTINUIRESOURCEPLUS: (BLKTYPE_OBJECTACTION, 5, (PARAMTYPE_SC_BLK_VARIABLES, PARAMTYPE_SD_TEXT, PARAMTYPE_SD_NUMBER, PARAMTYPE_SD_OBJECT, PARAMTYPE_SD_COLOR), (CT_COMBOBOX, CT_TEXTBOX, CT_NUMBERBOX, CT_COMBOBOX, CT_TEXTBOX)),
    BLKREFID_OS_DELETESELF: (BLKTYPE_OBJECTSETTING, 0, (), (CT_NONE, )),
    BLKREFID_OS_DISPLAYRESOURCE: (BLKTYPE_OBJECTSETTING, 1,
                                  (PARAMTYPE_SD_RESOURCE, ), (CT_COMBOBOX, )),
    BLKREFID_OS_HIDERESOURCE: (BLKTYPE_OBJECTSETTING, 1,
                               (PARAMTYPE_SD_RESOURCE, ), (CT_COMBOBOX, )),
    BLKREFID_OS_TOBESUBRESOURCEOFPICOFACILITYINOVERLAPPING:
    (BLKTYPE_OBJECTSETTING, 1, (PARAMTYPE_SD_PICOFACILITY, ), (CT_COMBOBOX, )),
    BLKREFID_OS_TOBESUBRESOURCEOFRESOURCEINOVERLAPPING:
    (BLKTYPE_OBJECTSETTING, 1, (PARAMTYPE_SD_RESOURCE, ), (CT_COMBOBOX, )),
    BLKREFID_OS_TOBESUBRESOURCEOFPICOFACILITYINORIGINALSTATE:
    (BLKTYPE_OBJECTSETTING, 1, (PARAMTYPE_SD_PICOFACILITY, ), (CT_COMBOBOX, )),
    BLKREFID_OS_TOBESUBRESOURCEOFRESOURCEINORIGINALSTATE:
    (BLKTYPE_OBJECTSETTING, 1, (PARAMTYPE_SD_RESOURCE, ), (CT_COMBOBOX, )),
    BLKREFID_OS_BREADAWAYFROWPARENTRESOURCE: (BLKTYPE_OBJECTSETTING, 0, (),
                                              (CT_NONE, )),
    BLKREFID_OS_GAMEOVER: (BLKTYPE_OBJECTSETTING, 0, (), (CT_NONE, )),
    BLKREFID_OS_CLONERESOURCE: (BLKTYPE_OBJECTSETTING, 1,
                                (PARAMTYPE_SD_RESOURCE, ), (CT_COMBOBOX, )),
    BLKREFID_OS_BROADCASTMESSAGE_P2P:
    (BLKTYPE_OBJECTSETTING, 2,
     (PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL,
      PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL | PARAMTYPE_SC_BLK_RESOURCE),
     (CT_NUMBERBOX, CT_NUMBERBOX)),
    BLKREFID_OS_SHOWVKB: (BLKTYPE_OBJECTSETTING, 0, (), (CT_NONE, )),
    BLKREFID_OS_HIDEVKB: (BLKTYPE_OBJECTSETTING, 0, (), (CT_NONE, )),
    BLKREFID_OS_OPENSSCREEN: (BLKTYPE_OBJECTSETTING, 0, (), (CT_NONE, )),
    BLKREFID_OS_CLOSESSCREEN: (BLKTYPE_OBJECTSETTING, 0, (), (CT_NONE, )),
    BLKREFID_OS_SWITCHSTARE: (BLKTYPE_OBJECTSETTING, 2,
                              (PARAMTYPE_SD_STATE, PARAMTYPE_SC_BLK_RESOURCE),
                              (CT_COMBOBOX, CT_COMBOBOX)),
    BLKREFID_OS_BROADCASTMESSAGE: (BLKTYPE_OBJECTSETTING, 1,
                                   (PARAMTYPE_SD_NUMBER
                                    | PARAMTYPE_SC_BLK_VARIABLES
                                    | PARAMTYPE_SC_BLKTYPE_DATACAL, ),
                                   (CT_NUMBERBOX, )),
    BLKREFID_OS_DISPLAY: (BLKTYPE_OBJECTSETTING, 0, (), (CT_NONE, )),
    BLKREFID_OS_HIDE: (BLKTYPE_OBJECTSETTING, 0, (), (CT_NONE, )),
    BLKREFID_CND_CRACHRESOURCE: (BLKTYPE_CONDITION, 1,
                                 (PARAMTYPE_SD_RESOURCE, ), (CT_COMBOBOX, )),
    BLKREFID_CND_NUMBERISOJZZZF: (BLKTYPE_CONDITION, 2,
                                  (PARAMTYPE_SD_NUMBER
                                   | PARAMTYPE_SC_BLK_VARIABLES
                                   | PARAMTYPE_SC_BLKTYPE_DATACAL,
                                   PARAMTYPE_SD_NUMBERTYPE), (CT_NUMBERBOX,
                                                              CT_COMBOBOX)),
    BLKREFID_CND_EXACTDIVISION:
    (BLKTYPE_CONDITION, 2,
     (PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
      | PARAMTYPE_SC_BLKTYPE_DATACAL, PARAMTYPE_SD_NUMBER
      | PARAMTYPE_SC_BLK_VARIABLES | PARAMTYPE_SC_BLKTYPE_DATACAL),
     (CT_NUMBERBOX, CT_NUMBERBOX)),
    BLKREFID_CND_BOOLANDOR: (BLKTYPE_CONDITION, 3,
                             (PARAMTYPE_SC_BLKTYPE_CONDITION,
                              PARAMTYPE_SD_OPERATORBOOL,
                              PARAMTYPE_SC_BLKTYPE_CONDITION),
                             (CT_CONDITIONBOX, CT_COMBOBOX, CT_CONDITIONBOX)),
    BLKREFID_CND_BOOLCOMPARE: (BLKTYPE_CONDITION, 3,
                               (PARAMTYPE_SD_NUMBER
                                | PARAMTYPE_SC_BLK_VARIABLES
                                | PARAMTYPE_SC_BLKTYPE_DATACAL,
                                PARAMTYPE_SD_OPERATORCOMPARE,
                                PARAMTYPE_SD_NUMBER
                                | PARAMTYPE_SC_BLK_VARIABLES
                                | PARAMTYPE_SC_BLKTYPE_DATACAL),
                               (CT_NUMBERBOX, CT_COMBOBOX, CT_NUMBERBOX)),
    BLKREFID_CND_BOOLNOT: (BLKTYPE_CONDITION, 1,
                           (PARAMTYPE_SC_BLKTYPE_CONDITION, ),
                           (CT_CONDITIONBOX, )),
    BLKREFID_CND_CAPTURE: (BLKTYPE_CONDITION, 1, (PARAMTYPE_SD_RESOURCE, ),
                           (CT_COMBOBOX, )),
    BLKREFID_CND_CHECKTYPE: (BLKTYPE_CONDITION, 2, (PARAMTYPE_SD_NUMBER,
                                                    PARAMTYPE_SD_TYPE),
                             (CT_NUMBERBOX, CT_COMBOBOX)),
    BLKREFID_CND_BOOLEANCONSTANT: (BLKTYPE_CONDITION, 1,
                                   (PARAMTYPE_SC_BLKTYPE_CONDITION, ),
                                   (CT_CONDITIONBOX, )),
    BLKREFID_CND_CONVERT2BOOLTYPE: (BLKTYPE_CONDITION, 1,
                                    (PARAMTYPE_SD_NUMBER, ), (CT_NUMBERBOX, )),
    BLKREFID_CND_EXISTINSTRING:
    (BLKTYPE_CONDITION, 2, (PARAMTYPE_SD_TEXT | PARAMTYPE_SC_BLK_VARIABLES,
                            PARAMTYPE_SD_TEXT | PARAMTYPE_SC_BLK_VARIABLES),
     (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_CND_EXISTINLIST: (BLKTYPE_CONDITION, 3,
                               (PARAMTYPE_SD_VARIABLES,
                                PARAMTYPE_SD_VARIABLESINCDEC,
                                PARAMTYPE_SD_CHANGEABLE),
                               (CT_TEXTBOX, CT_CONDITIONBOX, CT_CHANGEABLE)),
    BLKREFID_CND_COLLISIONCLONE: (BLKTYPE_CONDITION, 1,
                                  (PARAMTYPE_SD_RESOURCE, ), (CT_COMBOBOX, )),
    BLKREFID_CND_RUNTIMEENV: (BLKTYPE_CONDITION, 1,
                              (PARAMTYPE_SD_RUNTIMEENV, ), (CT_COMBOBOX, )),
    BLKREFID_CND_MOUSE_KEY_UPDOWN: (BLKTYPE_CONDITION, 2,
                                    (PARAMTYPE_SD_MOUSEKEY,
                                     PARAMTYPE_SD_HUMANACTION), (CT_COMBOBOX,
                                                                 CT_COMBOBOX)),
    BLKREFID_CND_MOUSE_MOVE: (BLKTYPE_CONDITION, 1,
                              (PARAMTYPE_SD_HUMANACTION, ), (CT_COMBOBOX, )),
    BLKREFID_CND_KB_KEY_UPDOWN: (BLKTYPE_CONDITION, 2,
                                 (PARAMTYPE_SD_HUMANACTION,
                                  PARAMTYPE_SD_BOARDKEY), (CT_COMBOBOX,
                                                           CT_COMBOBOX)),
    BLKREFID_CND_MOUSE_KEY_CLICK: (BLKTYPE_CONDITION, 1,
                                   (PARAMTYPE_SD_MOUSEKEY, ), (CT_COMBOBOX, )),
    BLKREFID_CND_VKB_KEY_UPDOWN: (BLKTYPE_CONDITION, 2,
                                  (PARAMTYPE_SD_HUMANACTION,
                                   PARAMTYPE_SD_BOARDKEY), (CT_COMBOBOX,
                                                            CT_COMBOBOX)),
    BLKREFID_CND_CLICK: (BLKTYPE_CONDITION, 0, (), (CT_NONE, )),
    BLKREFID_CND_STARE: (BLKTYPE_CONDITION, 0, (), (CT_NONE, )),
    BLKREFID_CND_VRHANDLE_KEY_UPDOWN: (BLKTYPE_CONDITION, 2,
                                       (PARAMTYPE_SD_HUMANACTION,
                                        PARAMTYPE_SD_PICOKEY), (CT_COMBOBOX,
                                                                CT_COMBOBOX)),
    BLKREFID_CND_VRHANDLE_KEY_CLICK: (BLKTYPE_CONDITION, 1,
                                      (PARAMTYPE_SD_PICOKEY, ),
                                      (CT_COMBOBOX, )),
    BLKREFID_CND_VRHANDLE_POINT: (BLKTYPE_CONDITION, 0, (), (CT_NONE, )),
    BLKREFID_CND_POCIKEYDOWNRELEASE: (BLKTYPE_CONDITION, 2,
                                      (PARAMTYPE_SD_HUMANACTION,
                                       PARAMTYPE_SD_PICOKEY), (CT_COMBOBOX,
                                                               CT_COMBOBOX)),
    BLKREFID_CND_ADSORPTION: (BLKTYPE_CONDITION, 2, (PARAMTYPE_SD_RESOURCE,
                                                     PARAMTYPE_SD_RESOURCE),
                              (CT_COMBOBOX, CT_COMBOBOX)),
    BLKREFID_VAR_VARIABLES: (BLKTYPE_VARIABLES, 1, (PARAMTYPE_SD_VARIABLES, ),
                             (CT_COMBOBOX, )),
    BLKREFID_VAR_STRING: (BLKTYPE_VARIABLES, 1, (PARAMTYPE_SD_TEXT, ), (CT_TEXTBOX, )),
    BLKREFID_VAR_OBJECT: (BLKTYPE_VARIABLES, 1, (PARAMTYPE_SD_RESOURCE, ),
                          (CT_COMBOBOX, )),
    BLKREFID_VAR_LIST: (BLKTYPE_VARIABLES, -1, (PARAMTYPE_SD_CHANGEABLE, ),
                        (CT_CHANGEABLE, )),
    BLKREFID_VAR_LIST_GET: (BLKTYPE_VARIABLES, 2, (PARAMTYPE_SD_VARIABLES,
                                                   PARAMTYPE_SD_NUMBER),
                            (CT_COMBOBOX, CT_TEXTBOX)),
    BLKREFID_VAR_STRING_JOINT: (BLKTYPE_VARIABLES, -1,
                                (PARAMTYPE_SD_CHANGEABLE, ), (CT_CHANGEABLE, )),
    BLKREFID_VAR_STRING_GETLENGTH: (BLKTYPE_VARIABLES, 0, (), (CT_NONE, )),
    BLKREFID_VAR_STRING_SUBCOUNT: (BLKTYPE_VARIABLES, 3,
                                   (PARAMTYPE_SC_BLK_VARIABLES,
                                    PARAMTYPE_SC_BLKTYPE_CONDITION,
                                    PARAMTYPE_SC_BLK_VARIABLES),
                                   (CT_TEXTBOX, CT_CONDITIONBOX, CT_TEXTBOX)),
    BLKREFID_VAR_STRING_FUNCTION: (BLKTYPE_VARIABLES, 2,
                                   (PARAMTYPE_SC_BLK_VARIABLES,
                                    PARAMTYPE_SC_BLKTYPE_CONDITION),
                                   (CT_TEXTBOX, CT_CONDITIONBOX)),
    BLKREFID_VAR_STRINGCHAR: (BLKTYPE_VARIABLES, 0, (), (CT_NONE, )),
    BLKREFID_VAR_STRINGLASTCHAR: (BLKTYPE_VARIABLES, 0, (), (CT_NONE, )),
    BLKREFID_VAR_STRINGSUBSTRPICK: (BLKTYPE_VARIABLES, 4,
                                    (PARAMTYPE_SC_BLK_VARIABLES,
                                     PARAMTYPE_SD_NUMBER, PARAMTYPE_SD_NUMBER,
                                     PARAMTYPE_SD_NUMBER),
                                    (CT_TEXTBOX, CT_NUMBERBOX, CT_NUMBERBOX,
                                     CT_NUMBERBOX)),
    BLKREFID_VAR_STRINGJOINTBYTOKEN: (BLKTYPE_VARIABLES, 2,
                                      (PARAMTYPE_SD_TEXT,
                                       PARAMTYPE_SD_VARIABLES), (CT_TEXTBOX,
                                                                 CT_COMBOBOX)),
    BLKREFID_VAR_STRINGSPLITLIMITCOUNT: (BLKTYPE_VARIABLES, 3,
                                         (PARAMTYPE_SD_VARIABLES,
                                          PARAMTYPE_SD_VARIABLES),
                                         (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_VAR_STRINGSUB: (BLKTYPE_VARIABLES, 3,
                             (PARAMTYPE_SD_VARIABLES, PARAMTYPE_SD_TEXT,
                              PARAMTYPE_SD_TEXT), (CT_COMBOBOX, CT_TEXTBOX,
                                                   CT_TEXTBOX)),
    BLKREFID_VAR_STRINGSUBCOUNT: (BLKTYPE_VARIABLES, 2, (PARAMTYPE_SD_TEXT,
                                                         PARAMTYPE_SD_TEXT),
                                  (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_VAR_STRINGREPLACE: (BLKTYPE_VARIABLES, 3,
                                 (PARAMTYPE_SD_VARIABLES, PARAMTYPE_SD_TEXT,
                                  PARAMTYPE_SD_TEXT), (CT_COMBOBOX, CT_TEXTBOX,
                                                       CT_TEXTBOX)),
    BLKREFID_VAR_LISTLASTITEM: (BLKTYPE_VARIABLES, 1,
                                (PARAMTYPE_SD_VARIABLES, ), (CT_COMBOBOX, )),
    BLKREFID_VAR_VARIABLESINCDEC: (BLKTYPE_VARIABLES, 3,
                                   (PARAMTYPE_SD_VARIABLES,
                                    PARAMTYPE_SD_VARIABLESINCDEC,
                                    PARAMTYPE_SD_NUMBER
                                    | PARAMTYPE_SC_BLK_VARIABLES
                                    | PARAMTYPE_SC_BLKTYPE_DATACAL),
                                   (CT_COMBOBOX, CT_COMBOBOX, CT_NUMBERBOX)),
    BLKREFID_VAR_VARIABLESASSIGNMENT: (BLKTYPE_VARIABLES, 2,
                                       (PARAMTYPE_SD_VARIABLES,
                                        PARAMTYPE_SD_NUMBER
                                        | PARAMTYPE_SC_BLK_VARIABLES
                                        | PARAMTYPE_SC_BLKTYPE_DATACAL),
                                       (CT_COMBOBOX, CT_NUMBERBOX)),
    BLKREFID_VAR_LIST_SET: (BLKTYPE_VARIABLES, 3,
                            (PARAMTYPE_SD_VARIABLES, PARAMTYPE_SD_NUMBER,
                             PARAMTYPE_SD_NUMBER
                             | PARAMTYPE_SC_BLK_VARIABLES
                             | PARAMTYPE_SC_BLKTYPE_DATACAL),
                            (CT_COMBOBOX, CT_TEXTBOX, CT_NUMBERBOX)),
    BLKREFID_VAR_LOG: (BLKTYPE_VARIABLES, 1,
                       (PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
                        | PARAMTYPE_SC_BLKTYPE_DATACAL, ), (CT_NUMBERBOX, )),
    BLKREFID_VAR_LIST_APPEND: (BLKTYPE_VARIABLES, 2,
                               (PARAMTYPE_SC_BLK_VARIABLES,
                                PARAMTYPE_SC_BLK_VARIABLES), (CT_COMBOBOX,
                                                              CT_TEXTBOX)),
    BLKREFID_VAR_LIST_INSERT: (BLKTYPE_VARIABLES, 3,
                               (PARAMTYPE_SC_BLK_VARIABLES,
                                PARAMTYPE_SC_BLK_VARIABLES,
                                PARAMTYPE_SC_BLK_VARIABLES),
                               (CT_COMBOBOX, CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_VAR_LIST_REMOVE: (BLKTYPE_VARIABLES, 2,
                               (PARAMTYPE_SC_BLK_VARIABLES,
                                PARAMTYPE_SC_BLK_VARIABLES), (CT_COMBOBOX,
                                                              CT_TEXTBOX)),
    BLKREFID_VAR_LISTSORT: (BLKTYPE_VARIABLES, 1,
                            (PARAMTYPE_SC_BLKTYPE_CONDITION, ),
                            (CT_CONDITIONBOX, )),
    BLKREFID_VAR_PLUSEQUEAL: (BLKTYPE_VARIABLES, 2,
                              (PARAMTYPE_SC_BLK_VARIABLES,
                               PARAMTYPE_SC_BLK_VARIABLES), (CT_COMBOBOX,
                                                             CT_TEXTBOX)),
    BLKREFID_VAR_REMOVETAIL: (BLKTYPE_VARIABLES, 1,
                              (PARAMTYPE_SC_BLK_VARIABLES, ), (CT_COMBOBOX, )),
    BLKREFID_PF_STARTPHYSICSENGINE: (BLKTYPE_PHYSICSFEATHER, 0, (),
                                     (CT_NONE, )),
    BLKREFID_PF_STOPPHYSICSENGINE: (BLKTYPE_PHYSICSFEATHER, 0, (),
                                    (CT_NONE, )),
    BLKREFID_PF_SETTINGMASS: (BLKTYPE_PHYSICSFEATHER, 1,
                              (PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
                               | PARAMTYPE_SC_BLKTYPE_DATACAL, ),
                              (CT_NUMBERBOX, )),
    BLKREFID_PF_OPENGRAVITY: (BLKTYPE_PHYSICSFEATHER, 0, (), (CT_NONE, )),
    BLKREFID_PF_CLOSEGRAVITY: (BLKTYPE_PHYSICSFEATHER, 0, (), (CT_NONE, )),
    BLKREFID_PF_FORCEFROMXYZBYCOORDINATE:
    (BLKTYPE_PHYSICSFEATHER, 4,
     (PARAMTYPE_SD_COORDINATE3, PARAMTYPE_SD_NUMBER
      | PARAMTYPE_SC_BLK_VARIABLES | PARAMTYPE_SC_BLKTYPE_DATACAL,
      PARAMTYPE_SD_COORDINATESYSTEM, PARAMTYPE_SD_OBJECT),
     (CT_NUMBERBOX, CT_COMBOBOX, CT_NUMBERBOX, CT_COMBOBOX)),
    BLKREFID_PF_TOBETRIGGER: (BLKTYPE_PHYSICSFEATHER, 0, (), (CT_NONE, )),
    BLKREFID_PF_TOBECOLLIDER: (BLKTYPE_PHYSICSFEATHER, 0, (), (CT_NONE, )),
    BLKREFID_PF_OPEN_COLLIDE: (BLKTYPE_PHYSICSFEATHER, 0, (), (CT_NONE, )),
    BLKREFID_PF_CLOSE_COLLIDE: (BLKTYPE_PHYSICSFEATHER, 0, (), (CT_NONE, )),
    BLKREFID_SD_PLAYSOUNDREPEAT: (BLKTYPE_SOUND, 1, (PARAMTYPE_SD_SOUND, ),
                                  (CT_MUSICBOX, )),
    BLKREFID_SD_PLAYSOUNDONCE: (BLKTYPE_SOUND, 1, (PARAMTYPE_SD_SOUND, ),
                                (CT_MUSICBOX, )),
    BLKREFID_SD_STOPSOUND: (BLKTYPE_SOUND, 0, (), (CT_NONE, )),
    BLKREFID_SD_TTS_START: (BLKTYPE_SOUND, 2, (PARAMTYPE_SD_SOUND,
                                               PARAMTYPE_SD_TEXT),
                            (CT_MUSICBOX, CT_TEXTBOX)),
    BLKREFID_SD_TTT_END: (BLKTYPE_SOUND, 0, (), (CT_NONE, )),
    BLKREFID_DC_VARIABLECELL: (BLKTYPE_DATACAL, 1,
                               (PARAMTYPE_SD_NUMBER
                                | PARAMTYPE_SC_BLK_VARIABLES
                                | PARAMTYPE_SC_BLKTYPE_DATACAL, ),
                               (CT_NUMBERBOX, )),
    BLKREFID_DC_ARITHMETIC: (BLKTYPE_DATACAL, 3,
                             (PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
                              | PARAMTYPE_SC_BLKTYPE_DATACAL,
                              PARAMTYPE_SD_OPERATORARITHMETIC,
                              PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
                              | PARAMTYPE_SC_BLKTYPE_DATACAL),
                             (CT_NUMBERBOX, CT_COMBOBOX, CT_NUMBERBOX)),
    BLKREFID_DC_RANDOMNUMBER: (BLKTYPE_DATACAL, 2,
                               (PARAMTYPE_SD_NUMBER
                                | PARAMTYPE_SC_BLK_VARIABLES
                                | PARAMTYPE_SC_BLKTYPE_DATACAL,
                                PARAMTYPE_SD_NUMBER
                                | PARAMTYPE_SC_BLK_VARIABLES
                                | PARAMTYPE_SC_BLKTYPE_DATACAL),
                               (CT_NUMBERBOX, CT_NUMBERBOX)),
    BLKREFID_DC_REMAINDER: (BLKTYPE_DATACAL, 2,
                            (PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
                             | PARAMTYPE_SC_BLKTYPE_DATACAL,
                             PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
                             | PARAMTYPE_SC_BLKTYPE_DATACAL), (CT_NUMBERBOX,
                                                               CT_NUMBERBOX)),
    BLKREFID_DC_GETRESOURCECOORDINATEXYZ3RA: (BLKTYPE_DATACAL, 3,
                                              (PARAMTYPE_SD_RESOURCE,
                                               PARAMTYPE_SD_COORDINATE9,
                                               PARAMTYPE_SD_COORDINATESYSTEM),
                                              (CT_COMBOBOX, CT_COMBOBOX,
                                               CT_COMBOBOX)),
    BLKREFID_DC_DISTANCEOF2RESOURCE: (BLKTYPE_DATACAL, 2,
                                      (PARAMTYPE_SD_RESOURCE,
                                       PARAMTYPE_SD_RESOURCE), (CT_COMBOBOX,
                                                                CT_COMBOBOX)),
    BLKREFID_DC_TEXTOFRESOUREUI: (BLKTYPE_DATACAL, 1,
                                  (PARAMTYPE_SD_RESOURCEUI, ),
                                  (CT_COMBOBOX, )),
    BLKREFID_DC_FUNCTIONPLUS: (BLKTYPE_DATACAL, 0, (), (CT_NONE, )),
    BLKREFID_DC_TYPE_TRANSLATE: (BLKTYPE_DATACAL, 2, (PARAMTYPE_SD_NUMBER,
                                                      PARAMTYPE_SD_TYPE),
                                 (CT_NUMBERBOX, CT_CONDITIONBOX)),
    BLKREFID_DC_GET_CURRENTTIME: (BLKTYPE_DATACAL, 0, (), (CT_NONE, )),
    BLKREFID_DC_PIE: (BLKTYPE_DATACAL, 1, (PARAMTYPE_SC_BLKTYPE_CONDITION, ),
                      (CT_CONDITIONBOX, )),
    BLKREFID_DC_STATICTICS: (BLKTYPE_DATACAL, 2,
                             (PARAMTYPE_SC_BLK_VARIABLES,
                              PARAMTYPE_SC_BLKTYPE_CONDITION),
                             (CT_COMBOBOX, CT_CONDITIONBOX)),
    BLKREFID_DC_FLOORCEIL: (BLKTYPE_DATACAL, 2,
                            (PARAMTYPE_SC_BLKTYPE_CONDITION,
                             PARAMTYPE_SD_TEXT), (CT_CONDITIONBOX,
                                                  CT_TEXTBOX)),
    BLKREFID_DC_ROUND: (BLKTYPE_DATACAL, 2, (PARAMTYPE_SD_TEXT,
                                             PARAMTYPE_SD_TEXT), (CT_TEXTBOX,
                                                                  CT_TEXTBOX)),
    BLKREFID_DC_GET_TIMEITEM: (BLKTYPE_DATACAL, 1,
                               (PARAMTYPE_SC_BLKTYPE_CONDITION, ),
                               (CT_CONDITIONBOX, )),
    BLKREFID_DC_FUNCTION: (BLKTYPE_DATACAL, 2,
                           (PARAMTYPE_SD_OPERATORFUNCTION,
                            PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
                            | PARAMTYPE_SC_BLKTYPE_DATACAL), (CT_COMBOBOX,
                                                              CT_NUMBERBOX)),
    BLKREFID_DC_TRIFUNCTION: (BLKTYPE_DATACAL, 2,
                              (PARAMTYPE_SD_OPERATORTRIFUNCTION,
                               PARAMTYPE_SD_NUMBER | PARAMTYPE_SC_BLK_VARIABLES
                               | PARAMTYPE_SC_BLKTYPE_DATACAL),
                              (CT_COMBOBOX, CT_NUMBERBOX)),
    BLKREFID_DRAW_MOVE: (BLKTYPE_DRAW, 3,
                         (PARAMTYPE_SD_PEN, PARAMTYPE_SC_BLKTYPE_CONDITION,
                          PARAMTYPE_SD_TEXT), (CT_TEXTBOX, CT_CONDITIONBOX,
                                               CT_TEXTBOX)),
    BLKREFID_DRAW_ROTATE: (BLKTYPE_DRAW, 3,
                           (PARAMTYPE_SD_PEN, PARAMTYPE_SC_BLKTYPE_CONDITION,
                            PARAMTYPE_SD_TEXT), (CT_TEXTBOX, CT_CONDITIONBOX,
                                                 CT_TEXTBOX)),
    BLKREFID_DRAW_MOVETO: (BLKTYPE_DRAW, 3,
                           (PARAMTYPE_SD_PEN, PARAMTYPE_SD_TEXT,
                            PARAMTYPE_SD_TEXT), (CT_TEXTBOX, CT_TEXTBOX,
                                                 CT_TEXTBOX)),
    BLKREFID_DRAW_XYMOVETO: (BLKTYPE_DRAW, 3,
                             (PARAMTYPE_SD_PEN, PARAMTYPE_SC_BLKTYPE_CONDITION,
                              PARAMTYPE_SD_TEXT), (CT_TEXTBOX, CT_CONDITIONBOX,
                                                   CT_TEXTBOX)),
    BLKREFID_DRAW_DRAWCIRCLE: (BLKTYPE_DRAW, 2, (PARAMTYPE_SD_TEXT,
                                                 PARAMTYPE_SD_TEXT),
                               (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_DRAW_DRAWPOLYGONS: (BLKTYPE_DRAW, 3,
                                 (PARAMTYPE_SD_PEN, PARAMTYPE_SD_TEXT,
                                  PARAMTYPE_SD_TEXT), (CT_TEXTBOX, CT_TEXTBOX,
                                                       CT_TEXTBOX)),
    BLKREFID_DRAW_DRAWDOT: (BLKTYPE_DRAW, 2, (PARAMTYPE_SD_PEN,
                                              PARAMTYPE_SD_TEXT),
                            (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_DRAW_DRAWTEXT: (BLKTYPE_DRAW, 2, (PARAMTYPE_SD_PEN,
                                               PARAMTYPE_SD_TEXT),
                             (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_DRAW_BRUSH: (BLKTYPE_DRAW, 0, (), (CT_NONE, )),
    BLKREFID_DRAW_SETNEWBRUSH: (BLKTYPE_DRAW, 1,
                                (PARAMTYPE_SC_BLK_VARIABLES, ), (CT_TEXTBOX, )),
    BLKREFID_DRAW_FACINGANGLE: (BLKTYPE_DRAW, 2, (PARAMTYPE_SD_PEN,
                                                  PARAMTYPE_SD_TEXT),
                                (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_DRAW_BRUSHSTATE: (BLKTYPE_DRAW, 2,
                               (PARAMTYPE_SD_PEN,
                                PARAMTYPE_SC_BLKTYPE_CONDITION),
                               (CT_TEXTBOX, CT_CONDITIONBOX)),
    BLKREFID_DRAW_BRUSHTHICKNESS: (BLKTYPE_DRAW, 2, (PARAMTYPE_SD_PEN,
                                                     PARAMTYPE_SD_TEXT),
                                   (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_DRAW_BRUSHSPEED: (BLKTYPE_DRAW, 2, (PARAMTYPE_SD_PEN,
                                                 PARAMTYPE_SD_TEXT),
                               (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_DRAW_GETBRUSHVALUE: (BLKTYPE_DRAW, 2,
                                  (PARAMTYPE_SD_PEN,
                                   PARAMTYPE_SC_BLKTYPE_CONDITION),
                                  (CT_TEXTBOX, CT_CONDITIONBOX)),
    BLKREFID_DRAW_SHOWORHIDEBRUSH: (BLKTYPE_DRAW, 2,
                                    (PARAMTYPE_SC_BLKTYPE_CONDITION,
                                     PARAMTYPE_SD_PEN), (CT_CONDITIONBOX,
                                                         CT_TEXTBOX)),
    BLKREFID_DRAW_CLEARBRUSH: (BLKTYPE_DRAW, 1, (PARAMTYPE_SD_PEN, ),
                               (CT_TEXTBOX, )),
    BLKREFID_DRAW_STOPBRUSH: (BLKTYPE_DRAW, 0, (), (CT_NONE, )),
    BLKREFID_DRAW_SETBACKGROUNDCOLOR: (BLKTYPE_DRAW, 1, (PARAMTYPE_SD_COLOR, ),
                                       (CT_TEXTBOX, )),
    BLKREFID_DRAW_SETBRUSHCOLOR: (BLKTYPE_DRAW, 2, (PARAMTYPE_SD_PEN,
                                                    PARAMTYPE_SD_COLOR),
                                  (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_DRAW_PRINT: (BLKTYPE_DRAW, -1, (PARAMTYPE_SD_TEXT, ),
                          (CT_TEXTBOX, )),
    BLKREFID_DRAW_ASKANDINPUT: (BLKTYPE_DRAW, 1, (PARAMTYPE_SD_TEXT, ),
                                (CT_TEXTBOX, )),
    BLKREFID_DRAW_GETINPUT: (BLKTYPE_DRAW, 0, (), (CT_NONE, )),
    BLKREFID_DRAW_OTHERPYTHONFUNCTION: (BLKTYPE_DRAW, 0, (), (CT_NONE, )),

    # 2021-10-14 新增
    BLKREFID_VAR_LOCALVARIABLES: (BLKTYPE_VARIABLES, 0, (), (CT_NONE, )),
    BLKREFID_LF_LOOP_STEP_NEW: (BLKTYPE_LOGICFLOW, 4,
                                (PARAMTYPE_SD_TEXT, PARAMTYPE_SD_NUMBER,
                                 PARAMTYPE_SD_NUMBER, PARAMTYPE_SD_NUMBER),
                                (CT_TEXTBOX, CT_NUMBERBOX, CT_NUMBERBOX,CT_NUMBERBOX)),
    BLKREFID_LF_LOOP_TRAVERSELIST_NEW: (BLKTYPE_LOGICFLOW, 2,
                                    (PARAMTYPE_SD_TEXT, PARAMTYPE_SD_TEXT),
                                    (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_CND_EXISTINLIST_NEW: (BLKTYPE_CONDITION, 3,
                               (PARAMTYPE_SD_TEXT, PARAMTYPE_SD_VARIABLESINCDEC,
                                PARAMTYPE_SD_TEXT),
                               (CT_TEXTBOX, CT_CONDITIONBOX, CT_TEXTBOX)),
    BLKREFID_VAR_VARIABLESINCDEC_NEW: (BLKTYPE_VARIABLES, 3,
                                   (PARAMTYPE_SD_TEXT,
                                    PARAMTYPE_SD_TEXT,
                                    PARAMTYPE_SD_NUMBER
                                    | PARAMTYPE_SC_BLK_VARIABLES
                                    | PARAMTYPE_SC_BLKTYPE_DATACAL),
                                   (CT_TEXTBOX, CT_TEXTBOX, CT_NUMBERBOX)),
    BLKREFID_VAR_VARIABLESASSIGNMENT_NEW: (BLKTYPE_VARIABLES, 2,
                                       (PARAMTYPE_SD_TEXT,
                                        PARAMTYPE_SD_NUMBER
                                        | PARAMTYPE_SC_BLK_VARIABLES
                                        | PARAMTYPE_SC_BLKTYPE_DATACAL),
                                       (CT_TEXTBOX, CT_NUMBERBOX)),
    BLKREFID_VAR_LIST_SET_NEW: (BLKTYPE_VARIABLES, 3, 
                                (PARAMTYPE_SD_TEXT, PARAMTYPE_SD_NUMBER, 
                                 PARAMTYPE_SD_NUMBER
                                 | PARAMTYPE_SC_BLK_VARIABLES
                                 | PARAMTYPE_SC_BLKTYPE_DATACAL),
                                (CT_TEXTBOX, CT_TEXTBOX, CT_NUMBERBOX)),
    BLKREFID_VAR_LIST_GET_NEW: (BLKTYPE_VARIABLES, 2,
                                (PARAMTYPE_SD_TEXT, PARAMTYPE_SD_NUMBER),
                                (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_VAR_STRINGJOINTBYTOKEN_NEW: (BLKTYPE_VARIABLES, 2,
                                      (PARAMTYPE_SD_TEXT,
                                       PARAMTYPE_SD_TEXT),
                                      (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_VAR_STRINGSUB_NEW: (BLKTYPE_VARIABLES, 3,
                                 (PARAMTYPE_SD_TEXT, PARAMTYPE_SD_TEXT, PARAMTYPE_SD_TEXT),
                                 (CT_TEXTBOX, CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_VAR_LIST_APPEND_NEW: (BLKTYPE_VARIABLES, 2,
                                   (PARAMTYPE_SD_TEXT,PARAMTYPE_SD_TEXT),
                                   (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_VAR_LIST_INSERT_NEW: (BLKTYPE_VARIABLES, 3,
                               (PARAMTYPE_SD_TEXT,
                                PARAMTYPE_SD_TEXT,
                                PARAMTYPE_SD_TEXT),
                               (CT_TEXTBOX, CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_VAR_LIST_REMOVE_NEW: (BLKTYPE_VARIABLES, 2,
                               (PARAMTYPE_SD_TEXT,
                                PARAMTYPE_SD_TEXT),
                               (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_VAR_LISTSORT_NEW: (BLKTYPE_VARIABLES, 1,
                            (PARAMTYPE_SD_TEXT, ),
                            (CT_TEXTBOX, )),
    BLKREFID_VAR_PLUSEQUEAL_NEW: (BLKTYPE_VARIABLES, 2,
                              (PARAMTYPE_SD_TEXT,
                               PARAMTYPE_SD_TEXT),
                              (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_VAR_REMOVETAIL_NEW: (BLKTYPE_VARIABLES, 1,
                                  (PARAMTYPE_SD_TEXT, ),
                                  (CT_TEXTBOX, )),
    BLKREFID_VAR_LISTLASTITEM_NEW: (BLKTYPE_VARIABLES, 1,
                                    (PARAMTYPE_SD_TEXT, ),
                                    (CT_TEXTBOX, )),
    BLKREFID_DC_STATICTICS_NEW: (BLKTYPE_DATACAL, 2,
                             (PARAMTYPE_SD_TEXT,
                              PARAMTYPE_SD_TEXT),
                             (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_DC_RANDOMINT: (BLKTYPE_DATACAL, 2,
                             (PARAMTYPE_SD_TEXT,
                              PARAMTYPE_SD_TEXT),
                             (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_OA_MOVEBYPATHWITHTIME: (BLKTYPE_OBJECTACTION, 2,
                             (PARAMTYPE_SD_TEXT,
                              PARAMTYPE_SD_TEXT),
                             (CT_TEXTBOX, CT_TEXTBOX)),
    BLKREFID_LF_LOOP_DEFAULT: (BLKTYPE_LOGICFLOW, 3,
                            (PARAMTYPE_SD_TEXT, PARAMTYPE_SD_NUMBER,
                             PARAMTYPE_SD_NUMBER),
                            (CT_TEXTBOX, CT_TEXTBOX, CT_TEXTBOX)),
}
# ###### trigger type ######
TRIGGERTYPE_NONE = -1  # 触发方式: 不触发
TRIGGERTYPE_WHEN_START = BLKREFID_TRG_WHENPROJECTSTART  # 触发方式: 当工程运行时
TRIGGERTYPE_WHEN_CLICK = BLKREFID_TRG_WHENSELFBEENCLICK  # 触发方式: 当自己被点击
TRIGGERTYPE_WHEN_BROADCAST = BLKREFID_TRG_WHENRECIEVEBROADCASTMESSAGE  # 触发方式: 当收到广播 (广播消息编号)
TRIGGERTYPE_WHEN_CONDITION = BLKREFID_TRG_WHENCONDITION  # 触发方式: 当 <条件表达式>
TRIGGERTYPE_WHEN_RUNNINGASCLONE = BLKREFID_TRG_WHENRUNNINGASCLONE  # 触发方式: 当作为克隆体启动时
TRIGGERTYPE_WHEN_MOUSEMOVING = BLKREFID_TRG_WHENMOUSEMOVING  # 触发方式: 当鼠标[移入|移除]自己时
TRIGGERTYPE_WHEN_MOUSELEFTKEY = BLKREFID_TRG_WHENMOUSELEFTKEYACTION  # 触发方式: 当鼠标左键[按下|松开]时
TRIGGERTYPE_WHEN_KEYBOARD = BLKREFID_TRG_WHENKEYBOARDACTION  # 触发方式: 当键盘[按下|抬起|持续按下][按键|......]时
TRIGGERTYPE_WHEN_PICOHANDLEPOINT = BLKREFID_TRG_WHENPICOHANDLECURSOR  # 触发方式: 当pico手柄指向
TRIGGERTYPE_WHEN_PICOKEY = BLKREFID_TRG_WHENPICOHANDLEACTION  # 触发方式: 当pico[按下|松开][圆盘键|扳机键]

#######################################################################################
###### evnet source type ######
EST_NONE = 0X0000000000000000  # none
EST_SYSTEM_STARTPOINTOR_GAMESTART = 0x0000000000000001  # fire when 工程运行时
EST_SYSTEM_PLATFORM = 0x0000000000000002  # fire when 平台触发是PC/VR
EST_PROGRAM_BROADCASTMSG = 0x0000000000000004  # fire when 广播消息
EST_PROGRAM_CLONE = 0x0000000000000008  # fire when 克隆体运行
EST_PROGRAM_WRITEVARIABLES = 0x0000000000000010  # fire when 改变变量
EST_GAMERUNING_CAPTURED = 0x0000000000000020  # fire when 被抓取(resource)
EST_GAMERUNING_ABSORBED = 0x0000000000000040  # fire when 被吸附(resource1,resource2)
EST_GAMERUNING_COLLIDED = 0x0000000000000080  # fire when 碰到(resource)
EST_HUMAN_CLICK = 0x0000000000000100  # fire when 被click
EST_HUMAN_MOUSE_CURSORIN = 0x0000000000000200  # fire when 鼠标光标移入
EST_HUMAN_MOUSE_CORSOROUT = 0x0000000000000400  # fire when 鼠标光标移除
EST_HUMAN_MOUSE_LEFTKEYCLICK = 0x0000000000000800  # fire when 鼠标左键按下
EST_HUMAN_MOUSE_LEFTKEYRELEASE = 0x0000000000001000  # fire when 鼠标左键抬起
EST_HUMAN_KEYBOARD_KEYBOARDCLICK = 0x0000000000002000  # fire when 键盘按键按下(KEYS)
EST_HUMAN_KEYBOARD_KEYBOARDRELEASE = 0x0000000000004000  # fire when 键盘按键抬起(KEYS)
EST_HUMAN_KEYBOARD_KEYBOARDCLICKS = 0x0000000000008000  # fire when 键盘按键持续按下(KEYS)
EST_HUMAN_PICO_PICOHANDLECURSOR = 0x0000000000010000  # fire when pico手柄指向
EST_HUMAN_PICO_PICOHANDLEKEYCLICK = 0x0000000000020000  # fire when 按下pico(圆盘键|扳机键)
EST_HUMAN_PICO_PICOHANDLEKEYRELEASE = 0x0000000000040000  # fire when 抬起pico(圆盘键|扳机键)
EST_PROGRAM_BROADCASTMSG_P2P = 0x0000000000080000  # fire when 广播消息 2012/12/12
EST_PROGRAM_BROADCASTMSG_ALL = 0x0000000000100000  # fire when 广播消息 2012/12/12

###### evnet source value type ######
ESVT_NONE = 0X0000000000000000  # 无参数消息源,或者没有消息
ESVT_NUMBER = 0x0000000000000001  # 数字类型,包括整数,浮点数(正数,负数,零)
ESVT_GAMEOBJECT = 0x0000000000000002  # gameobject
ESVT_VARIABLE = 0x0000000000000004  # 变量
"""
###
#       GAME : game base info + [game object info list]s      注: 全局变量记录在此,但不在串中体现
# GAMEOBJECT : gameobject base info + [script info list]s     注: 局部变量记录在此,并在串中体现
#     SCRIPT : script base info + [block info list]s
#      BLOCK : block info
#
#       GAME : "gamename" ^ "C:1|G:3" ^ GAMEOBJECT * ... GAMEOBJECT *
# GAMEOBJECT : "objectname" & "objectid" & "objecttype & "object attribute(name:type:value|...)s" & SCRIPT # SCRIPT... # SCRIPT & 坐标 & 变量(类型|ID|名称) % ... % 变量(类型|ID|名称)
#     SCRIPT : BLOCK ~ ... ~ BLOCK
#      BLOCK : sequence id @ ref id @ location info @ value info @
#
#       GAME : 测试游戏^C:1|G:3^
# GAMEOBJECT : "objectname" & "objectid" & "objecttype & "object attribute(name:type:value|...)s" & SCRIPT # SCRIPT... # SCRIPT & 坐标 & 变量(类型|ID|名称) % ... % 变量(类型|ID|名称)
#     SCRIPT : BLOCK ~ ... ~ BLOCK
#      BLOCK : sequence id @ ref id @ location info @ value info @
#
# sample:
#
游戏例子1
^
C:1|G:3
^
Root      & 1 & 0 & &  &0,0&0|55545|gA
*
Player    & 2 & 1 & &  &0,1600&
*
爆竹三     & 3 & 2 & &  1@4@-552.2653,1832.809,0@D:2@@~2@40@@D:3@4$1@~3@62@@@2$0|1$0@#4@7@-424.7472,1658.2,0@D:5@1$1@~5@103@@@1$1|1$0|1$0|1$0|2$0@&400,3200&1|55545|lA%1|55545|lB
*
魔法圈     & 4 & 2 & &  1@6@-395.4414,1216.576,0@D:2|I1:14@@~2@98@@I1:3|I2:10|I4:13@1$1|1$0|1$0|1$0|2$0@~3@54@@I1:4@1$4|1$3@~4@47@@I1:5@1$0@~5@47@@I1:6@1$0@~6@47@@I1:7@1$0@~7@49@@I1:8|I2:9@1$0|1$1@~8@48@@@1$0|2$0|1$0@~9@59@@@2$0@~10@54@@I1:11|I2:12@1$4|1$3@~11@55@@@2$0|1$0@~12@63@@@4$1|6$1@~13@48@@@1$0|2$0|1$0@~14@52@@I1:15|I2:16@2$0@~15@45@@@2$0|3$0@~16@57@@I1:17@@~17@52@@I2:18@2$0@~18@50@@@1$0|2$0@ &0,2000 &1|55546|aaa
*
蓝色文本框  & 5 & 2 & & &0,0&
*
矩形输入框  & 6 & 2 & & &0,0&1|56222|bbb%1|56222|ccc
*
女孩       & 7 & 2 & &  1@4@-375,2050,0@D:2@@~2@23@@M:5|D:15|I1:3@@~3@56@@I1:4@1$0|2$0|1$0@~4@59@@@2$1@~5@99@@D:6@@~6@17@@M:7|D:14@@~7@2@@D:8@1$2@~8@22@@D:9@1$5@~9@60@@D:10@2$1|3$0|1$1@~10@23@@M:13|I1:11@@~11@56@@I1:12@1$0|2$5|1$10@~12@59@@@2$1@~13@66@@@@~14@102@@@4$4@~15@41@@D:16@7$1033@~16@43@@@@&0,3600&1|56923|bb
*
海盗三    & 8 & 2 & &  1@98@-612.1673,1216.47,0@I1:2|I2:9|I4:12@1$1|1$0|1$0|1$0|2$0@~2@54@@I1:3@1$4|1$3@~3@47@@I1:4@1$0@~4@47@@I1:5@1$0@~5@47@@I1:6@1$0@~6@49@@I1:7|I2:8@1$0|1$1@~7@48@@@1$0|2$0|1$0@~8@59@@@2$0@~9@54@@I1:10|I2:11@1$4|1$3@~10@55@@@2$0|1$0@~11@63@@@4$1|6$1@~12@48@@@1$0|2$0|1$0@#13@6@-634.2041,1278.462,0@I1:14@@~14@52@@I1:15|I2:16@2$0@~15@45@@@2$0|3$0@~16@57@@I1:17@@~17@52@@I2:18@2$0@~18@50@@@1$0|2$0@&400,2800&1|58466|aaa
*
测试数据:
游戏例子1^C:1|G:3^Root&1&0&&&0,0&0|55545|gA*Player&2&1&&&0,1600&*爆竹三&3&2&&1@4@-552.2653,1832.809,0@D:2@@~2@40@@D:3@4$1@~3@62@@@2$0|1$0@#4@7@-424.7472,1658.2,0@D:5@1$1@~5@103@@@1$1|1$0|1$0|1$0|2$0@&400,3200&1|55545|lA%1|55545|lB*魔法圈&4&2&&1@6@-395.4414,1216.576,0@D:2|I1:14@@~2@98@@I1:3|I2:10|I4:13@1$1|1$0|1$0|1$0|2$0@~3@54@@I1:4@1$4|1$3@~4@47@@I1:5@1$0@~5@47@@I1:6@1$0@~6@47@@I1:7@1$0@~7@49@@I1:8|I2:9@1$0|1$1@~8@48@@@1$0|2$0|1$0@~9@59@@@2$0@~10@54@@I1:11|I2:12@1$4|1$3@~11@55@@@2$0|1$0@~12@63@@@4$1|6$1@~13@48@@@1$0|2$0|1$0@~14@52@@I1:15|I2:16@2$0@~15@45@@@2$0|3$0@~16@57@@I1:17@@~17@52@@I2:18@2$0@~18@50@@@1$0|2$0@&0,2000&1|55546|aaa*蓝色文本框&5&2&&&0,0&*矩形输入框&6&2&&&0,0&1|56222|bbb%1|56222|ccc*女孩&7&2&&1@4@-375,2050,0@D:2@@~2@23@@M:5|D:15|I1:3@@~3@56@@I1:4@1$0|2$0|1$0@~4@59@@@2$1@~5@99@@D:6@@~6@17@@M:7|D:14@@~7@2@@D:8@1$2@~8@22@@D:9@1$5@~9@60@@D:10@2$1|3$0|1$1@~10@23@@M:13|I1:11@@~11@56@@I1:12@1$0|2$5|1$10@~12@59@@@2$1@~13@66@@@@~14@102@@@4$4@~15@41@@D:16@7$1033@~16@43@@@@&0,3600&1|56923|bb*海盗三&8&2&&1@98@-612.1673,1216.47,0@I1:2|I2:9|I4:12@1$1|1$0|1$0|1$0|2$0@~2@54@@I1:3@1$4|1$3@~3@47@@I1:4@1$0@~4@47@@I1:5@1$0@~5@47@@I1:6@1$0@~6@49@@I1:7|I2:8@1$0|1$1@~7@48@@@1$0|2$0|1$0@~8@59@@@2$0@~9@54@@I1:10|I2:11@1$4|1$3@~10@55@@@2$0|1$0@~11@63@@@4$1|6$1@~12@48@@@1$0|2$0|1$0@#13@6@-634.2041,1278.462,0@I1:14@@~14@52@@I1:15|I2:16@2$0@~15@45@@@2$0|3$0@~16@57@@I1:17@@~17@52@@I2:18@2$0@~18@50@@@1$0|2$0@&400,2800&1|58466|aaa*
###
"""
# ##### 定义串的分隔符
SPLIT_INGAME1 = "^"
SPLIT_INGAME1_ATTR1 = "|"
SPLIT_INGAME1_ATTR2 = ":"
SPLIT_INGAME2 = "*"
SPLIT_INGAMEOBJECT1 = "&"
SPLIT_INGAMEOBJECT2_SCRIPT = "#"
SPLIT_INGAMEOBJECT2_COORDINATE = ","
SPLIT_INGAMEOBJECT2_VARIABLES1 = "%"
SPLIT_INGAMEOBJECT2_VARIABLES2 = "|"
SPLIT_INGAMEOBJECT2_ATTR1 = "|"
SPLIT_INGAMEOBJECT2_ATTR2 = ":"

SPLIT_INSCRIPT_BLOCK = "~"
SPLIT_INBLOCK_ATTRIBUTION5 = "@"
SPLIT_INBLOCK_LOCATION_VALUE_TYPE = "|"
SPLIT_INBLOCK_LOCATION_VALUE_DMI = ":"
SPLIT_INBLOCK_DEFAULT_VALUE_DEF = "|"
SPLIT_INBLOCK_DEFAULT_VALUE_ARGTYPE9 = "$"
SPLIT_INBLOCK_COORDINATE = ","

SPLIT_BLOCKDIST1 = "*"
SPLIT_BLOCKDIST2 = "|"

SPLIT_SCORE_GRAMMAR = "^"
SPLIT_SCORE_TOTAL_SUBENTRY = "*"
SPLIT_SCORE_SUBENTRYS = "&"
SPLIT_SCORE_SUBENTRYS_ITEM = "|"
SPLIT_GRAMMAR_TYPE = "*"
SPLIT_GRAMMAR_TYPE_REPORTENTRY = "@"
SPLIT_GRAMMAR_REPORTENTRY_EACH = "&"
SPLIT_GRAMMAR_REPORTENTRY_DETAILS = "%"
SPLIT_GRAMMAR_REPORTENTRY_DETAILS_POINT = "|"
SPLIT_GRAMMAR_REPORTENTRY_DETAILS_POINT_ITEM = ","

MAX_TIME = 999999999
MAX_BLOCKCOUNT = 999999999
MAX_NESTDEPTH = 999999999

# """
# 计分规则--CT
# """
# CT_STAGE_PRIMARY  = 0
# CT_STAGE_MIDDLE   = 1
# CT_STAGE_ADVANCED = 2
#
# CT_CONCEPT_ABSTRACTION_AND_PROBLEM_DECOMPOSITION = 0
# CT_CONCEPT_PARALLELISM                           = 1
# CT_CONCEPT_LOGICAL_THINKING                      = 2
# CT_CONCEPT_SYNCHRONIZATION                       = 3
# CT_CONCEPT_ALGORITHMIC_NOTIONS_OF_FLOW_CONTROL   = 4
# CT_CONCEPT_USER_INTERACTIVITY                    = 5
# CT_CONCEPT_DATA_REPRESENTATION                   = 6
# CT_CONCEPT_VA                                    = 7
#
# CT_Rule = {
# CT_CONCEPT_ABSTRACTION_AND_PROBLEM_DECOMPOSITION : (12,40,40,20,{},{},{}),
# CT_CONCEPT_PARALLELISM                           : (12,40,40,20,{},{},{}),
# CT_CONCEPT_LOGICAL_THINKING                      : (12,40,40,20,{},{},{}),
# CT_CONCEPT_SYNCHRONIZATION                       : (12,40,40,20,{},{},{}),
# CT_CONCEPT_ALGORITHMIC_NOTIONS_OF_FLOW_CONTROL   : (12,40,40,20,{},{},{}),
# CT_CONCEPT_USER_INTERACTIVITY                    : (12,40,40,20,{},{},{}),
# CT_CONCEPT_DATA_REPRESENTATION                   : (12,40,40,20,{},{},{}),
# CT_CONCEPT_VA                                    : (16,40,40,20,{},{},{})
# }
